### ISSUE TITLE
No trace context sometimes

### ISSUE THREAD

**Issue by emillg** [googleapis/cloud-trace-nodejs#1074]
## Environment details

  - OS: Linux
  - Node.js version: 5.12.0
  - npm version: 3.8.6
  - `@google-cloud/trace-agent` version: 4.1.0

#### Steps to reproduce
 I have a node.js express application receiving API calls from a Java application with B3 propagation. The tracer config looks like
```
const propagation = require('@opencensus/propagation-b3');

require('@google-cloud/trace-agent').start({
    projectId: XXX,
    serviceContext: {
        service: 'helloworld'
    },
    rootSpanNameOverride: ((path) => `http://helloworld${path}`),
    ignoreUrls: ['/health', '/metrics', '/api_version'],
    samplingRate: 1,
    propagation: new propagation.B3Format(),
    disableUntracedModulesWarning: true
});
```

The API code looks like
```
const tracer = require('@google-cloud/trace-agent');

exports.createDevice = async function (req, res) {
    log.info(req.headers);
    if (tracer.get().getCurrentRootSpan().getTraceContext()) {
        log.info(tracer.get().getCurrentRootSpan().getTraceContext());
    } else {
        log.info("No trace context");
    }
};
```

From the logs I can see the headers contain the B3 format tracing info. However, it's not able to retrieve the tracing info via Tracer.
```
{"timestamp":"2019-07-23T09:00:32.034Z","severity":"INFO","loggerName":"controller.js","message":{"accept":"application/json, application/*+json","content-type":"application/json","x-b3-traceid":"5d36ccae44c55278547b8e86c2fda48c","x-b3-spanid":"5a9093e6b77040d5","x-b3-parentspanid":"547b8e86c2fda48c","x-b3-sampled":"0","content-length":"176","user-agent":"Apache-HttpClient/4.5.5 (Java/1.8.0_181)","accept-encoding":"gzip,deflate"}
{"timestamp":"2019-07-23T09:00:32.034Z","severity":"INFO","loggerName":"controller.js","message":"No trace context"}
```

I would expect that the propagation should always happen when the headers contain B3 format info. Thanks!

**Comment by emillg** [comment]
@kjin Can you help with this issue? Thanks

**Comment by kjin** [comment]
Yep, will look into it momentarily!

**Comment by kjin** [comment]
My guess is that context is not lost because of B3 (or any) header propagation, but because some middleware earlier in the stack lost context. In other words I expect `getTraceContext()` to return null completely independently of whether there was an incoming trace context header (even if it's malformed).

Is the `createDevice` preceded by any additional middleware? If so, could you add those same log statements in the earliest possible middleware and see what they print? If it's something different than what you see currently, then that would suggest that some intermediate middleware is causing the problem.

**Comment by kjin** [comment]
Hi @emillg -- any update on this?

**Comment by kjin** [comment]
@emillg I'm closing this issue for housekeeping purposes, please comment if you have an update!

**Comment by emillg** [comment]
@kjin Sorry for my late response. It looks like the issue is caused by `app.use(bodyParser.json());`. Can you try to reproduce from your side? Thanks!

**Comment by kjin** [comment]
Sorry, I still can't seem to reproduce the issue.

For the record, I am using [this snippet](https://gist.github.com/kjin/8958108430d88e5c9e2d89c4bc40a6c2) to test. It's just a fibonacci server, just so I can make it send requests to itself with real B3 propagation headers via `curl localhost:8080/?n=2` instead of me having to type them myself.

By default, it always has trace context. But when I uncomment the lines marked with `// Purposely lose context`, it starts printing `No trace context`. That's why I'm wondering if you had any other middleware -- basically anything that might do userspace queueing the same way that the `// Purposely lose context` lines act. Since `body-parser` just uses `JSON.parse` under the hood, I wouldn't expect it to be the problem module. Is there anything else that might cause userspace queueing?

I might also be wrong -- can you elaborate on how you determined that the issue is caused by `body-parser`?

**Comment by kjin** [comment]
Hi @emillg -- any update on this?

**Comment by kjin** [comment]
@emillg I'm closing this issue again for housekeeping purposes, please comment if you have an update!
