### ISSUE TITLE
superagent creates phantom child span

### ISSUE THREAD

**Issue by bryanlarsen** [googleapis/cloud-trace-nodejs#1075]
When I use superagent, I get the message:

    @google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [http@10.16.0:http] Creating phantom child span [192.168.103.225] because there is no root span.

When I use axios instead, it appears to work:

    @google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [http@10.16.0:http] Created child span [192.168.103.225]

Versions:

Node: v10.16.0
│  ├─ axios@^0.19.0
├─ @google-cloud/trace-agent@4.1.0
├─ superagent@3.8.3

**Comment by bryanlarsen** [comment]
I turned on logging:       `@google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [http@10.16.0:http] Creating phantom child span [192.168.103.225] because there is no root span.`

So problem does appear to be PBKAC.   I will edit title appropriately soon.

**Comment by kjin** [comment]
Thanks for reporting this, I'll take a look!

**Comment by kjin** [comment]
Hi @bryanlarsen -- this problem is the result of https://github.com/nodejs/node/issues/22360, as superagent makes requests from the body of a custom thenable `then` implementation. (The bug itself is that code that runs within a `then` implementation, when awaited, loses context; we rely on this context to accurately correlate child spans to root spans.)

We are no longer writing new plugins for this module, so as a workaround, please try using this "unofficial" plugin I've written below:

https://gist.github.com/kjin/61230fb50dcb6b6474ba83ad1df6a09d

It hooks into superagent's `Request` constructor to patch the `Request#end` method (which is called from `Request#then`, and makes the request) to preserve context. You can load a custom plugin with:

```js
const tracer = require('@google-cloud/trace-agent')
  .start({
    plugins: {
      superagent: `${__dirname}/plugin-superagent.js`
    }
  });
```

Keep in mind that existing plugins are not affected.

Once the issue linked above is resolved, this plugin should no longer be needed.

**Comment by kjin** [comment]
Hi @bryanlarsen -- did you get a chance to look at this?

**Comment by kjin** [comment]
@bryanlarsen I'm closing this issue for housekeeping purposes, please comment if you have an update!
