### ISSUE TITLE
Trace agent spams our stderr due to large number of redis commands 

### ISSUE THREAD

**Issue by klon** [googleapis/cloud-trace-nodejs#1265]
Some of our requests trigger large clean ups in our Redis cache causing the creation of a large amount of child spans. This in turn creates thousands of stderr log lines making the stderr log unusable. We can't use ignoreUrls because many requests to the same URL are ok and we want to trace those. Also we can't know before hand how many redis del commands there will be, it could be tens of thousands. How can we avoid this? Ideally we would just want to limit the number of child spans and not log anything.

The log lines looks like this:

@google-cloud/trace-agent ERROR TraceApi#createChildSpan: [redis@3.0.2] Creating phantom child span [redis-del] because the trace with root span [/some/url] has reached a limit of 3200 spans. This is likely a memory leak.

**Comment by kjin** [comment]
Thanks for reporting this! It seems reasonable to want to have an upper limit without reporting.

By the way, IIRC, I don't think the Stackdriver Trace API allows more than 1000 spans per trace anyway, so I believe raising the hard upper limit to 3200 is unnecessary.

I haven't thought through all aspects of it, but let's say that we change the behavior so that no matter what `spansPerTraceHardLimit` is set to, we cut off spans actually published to the Stackdriver Trace API at 1000. That way, you could set `spansPerTraceHardLimit` to an exceedingly high number and it would basically never log (and if it did, it would actually indicate a real problem). What do you think?

**Comment by klon** [comment]
Thanks for reply! That sounds good. My only concern is potential memory usage and performance of allowing unlimited number of child spans in our app that will then eventually be discarded. Ideally the creation in the agent code would be limited as well.

**Comment by klon** [comment]
Thinking a little more on this.. Maybe the best fix is to make `spansPerTraceHardLimit` limit creation in the agent to reduce performance cost and just change the log level to WARN for those log lines, then we can choose to only log ERRORs and they would not clutter stderr.

**Comment by kjin** [comment]
Sure, we can do that. I was hesitant before because this might mask error messages from other users when they might be having real problems. But looking at the rest of the logging points at warn-level, I don't think it's too unreasonable for us to ask users to enable warn-level logging before reporting issues.
