### ISSUE TITLE
SpanType.DISABLED is set for firestore triggers

### ISSUE THREAD

**Issue by manwithsteelnerves** [googleapis/cloud-trace-nodejs#1369]
1) Is this a client library issue or a product issue?
Product behaviour

2) Did someone already solve this?
Nope

3) Do you have a support contract?
No

#### Environment details

  - Node.js version: Node 14
  - npm version:
  - `@google-cloud/trace-agent` version: 5.1.3

#### Steps to reproduce

  1. Print a span in firestore trigger
  2. Observe  type: 'DISABLED' is printed

Any way to enable it forcefully?

Note: The issue is not observed in firestore emulator (which is an another issue as its inconsistent - @abeisgoat)

Thanks!

**Comment by manwithsteelnerves** [comment]
Hey,
We checked earlier and noticed that spans are not tracked from cloud firestore triggers. This means the required tags are not added to the request to get parsed by cloud trace middleware.

I'm not sure if this is a regression but this is a quite basic feature to expect. Also there is no where in the documentation which mentions that distributed tracing is not supported by triggers.

**Comment by michaelsafyan** [comment]
Thanks for the additional context. Based on your explanation, I have filed two internal bugs:

  - Internal bug ID #205695613: trace context propagation to pubsub in Cloud Firestore
  - Internal bug ID #205696707: trace context propagation from pubsub to Cloud Functions for Firebase 

I believe these internal services are a better home for this request. Therefore, closing the bug here.
