### ISSUE TITLE
Mongoose v6 not being traced automatically 

### ISSUE THREAD

**Issue by lucamazzilli** [googleapis/cloud-trace-nodejs#1401]
#### Environment details

  - OS: Win 10 x64
  - Node.js version: 16.13.0
  - npm version: 8.1.0
  - `@google-cloud/trace-agent` version: 5.1.5
  - Mongoose: 6.0.10

#### Steps to reproduce

  1. start traceAgent using mongoose 6.0.10
  2. observe the error @google-cloud/trace-agent WARN PluginLoader#onRequire: [mongoose@6.0.10] This module is not supported by the configured set of plugins.

**Comment by gkf** [comment]
Unfortunately only mongoose v4 - v5 is supported according to: https://github.com/googleapis/cloud-trace-nodejs#what-gets-traced. As a workaround, one option is to use the [custom tracing API](https://github.com/googleapis/cloud-trace-nodejs#custom-tracing-api) to manually add spans.

I will leave this bug open as a feature request to support mongoose v6. However this is not likely to be prioritized because most development work is going into OpenTelemetry now. Contributed pull requests are always welcome though.

**Comment by punya** [comment]
[opentelemetry-instrumentation-mongoose](https://www.npmjs.com/package/opentelemetry-instrumentation-mongoose) seems to be active. I raised an issue to [ask if they support v6](https://github.com/aspecto-io/opentelemetry-ext-js/issues/239).

**Comment by punya** [comment]
According to https://github.com/googleapis/cloud-trace-nodejs/issues/1382#issuecomment-988153600, the OTel mongoose instrumentation supports v6. Closing this issue.

**Comment by Wazbat** [comment]
Sorry for pinging this old thread, but I wanted to ask. Are we able to use those opentelemetry instrumentations as plugins for this library? I'm a little confused by the readme
