### ISSUE TITLE
[Feature] configuration option: only trace when x-cloud-trace-context is set

### ISSUE THREAD

**Issue by 6utt3rfly** [googleapis/cloud-trace-nodejs#879]
When working in cross-service tracing contexts, I would like to define policies and filters at the ingress service and not have to also set the same url filters on each of the microservices. It would be nice if I could set all but the public trace server to require the header to be set, and then I could rate limit and filter just on the public microservice.

Since the `x-cloud-trace-context` is used for tracing spans, would a filter based on the header being set or not be easy to add?

https://github.com/googleapis/cloud-trace-nodejs/blob/f8b74e6ec0af23adb531ff48aa18ad1d89703834/doc/trace-api.md#cross-service-trace-contexts

**Comment by ofrobots** [comment]
Hi @6utt3rfly! Thanks for opening the issue. Today, we don't use the existence of the header as a mechanism to control tracing because headers are provided by the client which is untrusted on publicly exposed services. For private micro-services your suggestion makes sense and I'd be +1 on a config option user can explicitly enable.

Do you want to send a PR for this 😀?

**Comment by kjin** [comment]
Hi @6utt3rfly -- we've fixed this in 3.3.0. You can now pass the following options for non-public services to force sampling decisions to only be made on the first service:

```js
{
  samplingRate: 0,
  contextHeaderBehavior: 'require'
}
```

Please let us know if there are additional issues that need to be addressed!

**Comment by 6utt3rfly** [comment]
That is great @kjin ! I was going to try creating a PR this past weekend but I'm glad you beat me to it :-) I'll try to implement it this week and let you know if I have any problems. Thank you!
