### ISSUE TITLE
Issues when enabling tracing on gRPC service

### ISSUE THREAD

**Issue by a0viedo** [googleapis/cloud-trace-nodejs#952]
We were using the latest version of this module but after enabling it we couldn't see any traces whatsoever. After digging we found many of logs with
```
 severity:  "ERROR"  
 textPayload:  "original object and wrapper must be functions"
```
We believe it's because of the type checking one of the dependencies is doing ([see PR](https://github.com/othiym23/shimmer/pull/14)). We found also that switching to versions older to v3.5.0 seems to solve the problem.

Any idea on how to solve the issue for the latest version?

**Comment by a0viedo** [comment]
Ok got a reproduction: new VM on GCP with this [example](https://github.com/grpc/grpc/tree/v1.17.1/examples/node/dynamic_codegen/route_guide) running:
```
alejandro_oviedo_g@instance-1:~/grpc/examples/node/dynamic_codegen/route_guide$ node -v
v8.15.0
alejandro_oviedo_g@instance-1:~/grpc/examples/node/dynamic_codegen/route_guide$ node route_guide_server.js --db_path=./route_guide_db.json 
original object and wrapper must be functions
(node:3834) DeprecationWarning: Server#addProtoService: Use Server#addService instead
```

Run the client twice, first without any changes and the second time changing `routeChat` to be an async function. On Stackdriver I see both first calls but no routeChat for the second execution
![image](https://user-images.githubusercontent.com/2440935/51257196-d6681180-1985-11e9-9b5a-e4b2f30992e5.png)

**Comment by kjin** [comment]
Your `shimmer` PR should fix the problem! That being said this bug appears to be in all versions of the module -- it's not specific to 3.5.0.

Since `grpc` is the only module in which a user's function is directly wrapped via `shimmer` when it's patched for tracing, I'll go ahead and also open a PR to fix this issue here if the `shimmer` PR takes too long to land.

Thanks for bringing this to our attention!
