### ISSUE TITLE
Custom Tracing API supports the OpenTracing API

### ISSUE THREAD

**Issue by Downchuck** [googleapis/cloud-trace-nodejs#965]
[OpenTracing Javascript](https://github.com/opentracing/opentracing-javascript) has a very similar API surface and could be supported by cloiud-trace-nodejs through opentracing.initGlobalTracer provided a few support methods were added.

Here are some mappings of the API surface

| cloud-trace | opentracing |
| :------- | -------: |
| tracer.runInRootSpan | tracer.startSpan |
| tracer.createChildSpan | tracer.startSpan({childOf: parent}) |
| span.endSpan | span.finish |

By convention folk usually add the root tracer of a request to "req.span", though the technique used on cloud-trace is novel.

**Comment by Downchuck** [comment]
See also, for that wonderful approach to supporting things; https://github.com/googleapis/cloud-trace-nodejs/issues/304 -- Swagger and OpenTracing may not be well connected at the moment, but this might do that.

**Comment by ofrobots** [comment]
@Downchuck we are currently focussing on getting the [OpenCensus libraries for Node.js](https://github.com/census-instrumentation/opencensus-node) up and running. They should cover this use-case and more. At this point it probably makes sense to open this feature request over there.

I'm going to close the issue here. Please leave a comment here if you disagree with the disposition here.
