### ISSUE TITLE
Feature request: ability to trace headers

### ISSUE THREAD

**Issue by paglias** [googleapis/cloud-trace-nodejs#978]
Hi,

would it be possible to add a config option that when enabled adds the http headers and their content to http traces? Using express

As our API uses headers for authentication it would make it much easier to have the headers logged in the traces so that we can link them to the user that made them

thanks!

**Comment by kjin** [comment]
Hi @paglias -- would it work for you to use the custom tracing API to add specific header values as labels? Here's an example:

```js
const tracer = require('@google-cloud/trace-agent').start();
const express = require('express');

const app = express();

app.get('/', (req, res) => {
  const userId = req.header('User-ID');
  if (userId) {
    // Get the current root span, then add a label on it.
    // If the request wasn't sampled, this will be a no-op.
    tracer.getCurrentRootSpan().addLabel('userId', userId);
  }
  res.send(200);
});

app.listen(8080);
```

If this doesn't work for you let us know. Since you are seeking to read specific header values I'm not quite sure yet that it would be beneficial to have this feature implemented as part of the library itself, though we can discuss that if you think it makes sense for this functionality to be built-in.

**Comment by paglias** [comment]
Thanks @yoshi-automation, this is going to be enough for our use case so I'll close the issue. That being said I still think it would be useful to add more info when tracing http requests in order to be able to better filter them by user agent/headers/...
