### ISSUE TITLE
Seems like `runInRootSpan` doesn't work in async mode

### ISSUE THREAD

**Issue by istarkov** [googleapis/cloud-trace-nodejs#986]
This 
```javascript
const traceAgent = require('@google-cloud/trace-agent');
const tracer = traceAgent.start();
tracer.runInRootSpan({ name: 'works' }, rootSpan => {
  const readFileSpan = tracer.createChildSpan({ name: 'fs.readFile' });
  readFileSpan.endSpan();
  rootSpan.endSpan();
});
```
works, but in most cases `fs.readFile` span is not visible at traces.

But this
```javascript
const traceAgent = require('@google-cloud/trace-agent');

const tracer = traceAgent.start();

tracer.runInRootSpan({ name: 'not_works' }, rootSpan => {
  const readFileSpan = tracer.createChildSpan({ name: 'fs.readFile' });
  setTimeout(() => {
    readFileSpan.endSpan();
    rootSpan.endSpan();
  }, 1000);
});
```

doesn't work at all, I see no traces at all.

tested on `node 8.15.1`

**Comment by istarkov** [comment]
Seems like passing `{ bufferSize: 1 }` to start, solves the issue, but isn't any way exists to force traces flush?

**Comment by istarkov** [comment]
BTW even with `{ bufferSize: 1 }` I see childSpan are regularly skipped and not visible in traces

**Comment by kjin** [comment]
Hi @istarkov -- thanks for reporting the issue. It's true that we don't force spans to publish when the program exit, as in the past our typical use case would be that of a running server, where the last few traces that were queued if a server is shutdown under non-failure conditions may not all that important. I understand that the code snippets you provided are more of a minimum repro -- but if you are running scripts where you would need to publish traces on program exit let us know, we can support that.

Re: the second issue on childSpan regularly being skipped -- the Cloud Console Trace UI won't show spans if they are 0ms in duration, which is possible in your `works` repro. I don't expect it to be an issue in the `not_works` repro since the spans must be at least 1000ms long.

**Comment by istarkov** [comment]
Thank you, now I get why childSpans are skipped.
And I don't need publish traces on program exit as my use case is also typical ;-) just initial playing with simple example caused questions, on server all is fine.

Thank you for the answer again.
